This is makeindex, version 2.16 [MiKTeX 25.12].
Scanning style file ./compendium.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file compendium.acn....done (7 entries accepted, 0 rejected).
Sorting entries....done (23 comparisons).
Generating output file compendium.acr....done (23 lines written, 0 warnings).
Output written in compendium.acr.
Transcript written in compendium.alg.
